import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "id" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  id: {
    // Navbar
    "nav.features": "Fitur",
    "nav.pricing": "Harga",
    "nav.contact": "Kontak",
    
    // Hero
    "hero.badge": "Video Reaction Generator dengan AI",
    "hero.title.reactify": "Reactify",
    "hero.title.main": "Bikin Video Reaksi Viral dalam Hitungan Menit",
    "hero.description": "Video reaksi otomatis, profesional, dan siap upload. Powered by AI untuk content creator yang ingin viral!",
    "hero.cta.start": "Mulai Sekarang",
    "hero.cta.features": "Lihat Fitur",
    "hero.stat.voices": "30+ Suara AI",
    "hero.stat.subtitle": "Auto Subtitle",
    "hero.stat.bulk": "Bulk Processing",
    
    // Demo
    "demo.badge": "Demo Video",
    "demo.title": "Lihat Reactify Beraksi",
    "demo.subtitle": "Tonton bagaimana Reactify mengubah video biasa menjadi konten reaksi viral dalam hitungan menit",
    "demo.description": "Video demo menunjukkan seluruh proses dari memilih video hingga hasil akhir yang siap upload",
    
    // Problem
    "problem.title": "Mengapa Harus",
    "problem.title.highlight": "Reactify?",
    "problem.description": "Bikin video reaksi yang viral memakan banyak waktu. Dengan Reactify, semua jadi otomatis.",
    "problem.without.title": "Tanpa Reactify",
    "problem.without.subtitle": "Ribet & Memakan Waktu",
    "problem.without.1": "Rekam audio narasi manual",
    "problem.without.2": "Edit video satu per satu",
    "problem.without.3": "Tambahkan subtitle secara manual",
    "problem.without.4": "Pasang watermark & musik",
    "problem.without.5": "Render berulang kali",
    "problem.without.6": "Total waktu: Berjam-jam per video",
    "problem.with.title": "Dengan Reactify",
    "problem.with.subtitle": "Cepat, Mudah & Otomatis",
    "problem.with.1": "Pilih video target",
    "problem.with.2": "AI generate narasi otomatis",
    "problem.with.3": "Subtitle otomatis dalam detik",
    "problem.with.4": "Watermark & musik auto-apply",
    "problem.with.5": "Bulk processing banyak video sekaligus",
    "problem.with.6": "Total waktu: Hitungan menit!",
    
    // Features
    "features.title": "Fitur",
    "features.title.highlight": "Unggulan",
    "features.description": "Semua yang kamu butuhkan untuk bikin video reaksi profesional dan viral",
    "features.narration.title": "Narasi AI Otomatis",
    "features.narration.desc": "30+ pilihan suara Gemini TTS dengan berbagai gaya: lucu, dramatis, investigatif, edukatif, dan lainnya.",
    "features.subtitle.title": "Auto Subtitle",
    "features.subtitle.desc": "Generate subtitle otomatis dengan Whisper AI. Mendukung banyak bahasa dan customizable styling.",
    "features.music.title": "Musik Latar & Custom Audio",
    "features.music.desc": "Tambahkan background music agar video lebih hidup. Atur volume dan gunakan audio eksternal.",
    "features.watermark.title": "Watermark & Branding",
    "features.watermark.desc": "Lindungi video dengan watermark teks atau logo. Atur posisi, ukuran, dan opacity sesuai kebutuhan.",
    "features.overlay.title": "Video Overlay",
    "features.overlay.desc": "Tambahkan video overlay manual untuk reaction. Mode split atau corner dengan auto overlay.",
    "features.ai.title": "AI Judul Otomatis",
    "features.ai.desc": "Generate judul video catchy & SEO-friendly secara otomatis untuk maksimalkan views.",
    "features.bulk.title": "Bulk Processing",
    "features.bulk.desc": "Proses banyak video sekaligus dalam satu folder. Hemat waktu untuk produksi massal.",
    "features.ui.title": "Tampilan Modern",
    "features.ui.desc": "UI modern dengan Dark/Light Mode. Navigasi mudah dengan tab Log, Info Video, Script & Settings.",
    
    // Target Audience
    "audience.title": "Siapa yang Cocok",
    "audience.title.highlight": "Pakai Reactify?",
    "audience.1.title": "YouTuber & TikToker",
    "audience.1.desc": "Konten reaksi cepat jadi & siap viral",
    "audience.2.title": "Content Creator Meme",
    "audience.2.desc": "Editing instan untuk short video",
    "audience.3.title": "Brand & Influencer",
    "audience.3.desc": "Tambah watermark & branding otomatis",
    "audience.4.title": "Agency/Freelancer",
    "audience.4.desc": "Proses banyak video untuk klien",
    
    // How it works
    "howitworks.title": "Cara Kerja",
    "howitworks.title.highlight": "Reactify",
    "howitworks.description": "Hanya 3 langkah sederhana untuk video reaksi profesional",
    "howitworks.step1.title": "Pilih Video",
    "howitworks.step1.desc": "Upload atau pilih video yang ingin diproses",
    "howitworks.step2.title": "Atur Preferensi",
    "howitworks.step2.desc": "Setting narasi, subtitle, musik, watermark, dan overlay",
    "howitworks.step3.title": "Generate & Done",
    "howitworks.step3.desc": "Klik generate, tunggu sebentar, video reaksi siap upload!",
    
    // Pricing
    "pricing.title": "Harga",
    "pricing.title.highlight": "Spesial",
    "pricing.description": "Investasi kecil untuk produktivitas besar",
    "pricing.badge": "Lisensi Resmi & Aman",
    "pricing.per.year": "/ tahun",
    "pricing.license": "1 lisensi untuk 1 device",
    "pricing.feature.1": "Semua fitur lengkap tanpa batasan",
    "pricing.feature.2": "30+ suara AI Gemini TTS",
    "pricing.feature.3": "Auto subtitle multi-bahasa",
    "pricing.feature.4": "Bulk processing unlimited",
    "pricing.feature.5": "Watermark & branding custom",
    "pricing.feature.6": "Video overlay manual & auto",
    "pricing.feature.7": "AI judul otomatis",
    "pricing.feature.8": "Update versi terbaru gratis",
    "pricing.feature.9": "Support via WhatsApp",
    "pricing.license.year": "Lisensi berlaku 1 tahun penuh",
    "pricing.license.support": "Gratis update & support",
    "pricing.cta": "Aktivasi Sekarang via WhatsApp",
    
    // CTA
    "cta.title": "Jangan Buang Waktu Lagi Edit Manual",
    "cta.description": "Dengan Reactify, kamu bisa fokus bikin ide konten, biar urusan editing dikerjakan AI otomatis.",
    "cta.button": "Chat via WhatsApp",
    "cta.contact": "atau hubungi:",
    "cta.stat.voices": "Suara AI",
    "cta.stat.faster": "Lebih Cepat",
    "cta.stat.auto": "Otomatis",
    
    // Footer
    "footer.tagline": "Video Reaction Generator dengan AI",
    "footer.product": "Produk",
    "footer.features": "Fitur",
    "footer.pricing": "Harga",
    "footer.howitworks": "Cara Kerja",
    "footer.support": "Dukungan",
    "footer.contact": "Kontak",
    "footer.whatsapp": "WhatsApp",
    "footer.email": "Email",
    "footer.developed": "Dikembangkan oleh",
    "footer.rights": "All rights reserved.",
    
    // Benefits
    "benefits.title": "Mengapa Pilih",
    "benefits.title.highlight": "Reactify?",
    "benefits.description": "Manfaat nyata yang langsung kamu rasakan untuk bisnis konten kamu",
    "benefits.time.title": "Hemat Waktu Drastis",
    "benefits.time.desc": "Yang tadinya butuh berjam-jam editing, sekarang cuma hitungan menit. Fokus ke ide konten, bukan editing.",
    "benefits.time.stat": "Hemat Waktu",
    "benefits.viral.title": "Konten Lebih Produktif",
    "benefits.viral.desc": "Produksi 3x lebih banyak video dalam waktu yang sama. Lebih banyak konten = lebih banyak kesempatan viral.",
    "benefits.viral.stat": "Lebih Produktif",
    "benefits.cost.title": "ROI Maksimal",
    "benefits.cost.desc": "Investasi sekali, pakai setahun penuh. Hemat biaya editor, software editing premium, dan waktu produksi.",
    "benefits.cost.stat": "ROI Positif",
    "benefits.quality.title": "Kualitas Konsisten",
    "benefits.quality.desc": "Output video selalu HD dengan kualitas profesional. Subtitle rapi, audio jernih, branding konsisten.",
    "benefits.quality.stat": "Output",
    "benefits.speed.title": "Proses Super Cepat",
    "benefits.speed.desc": "Dari video mentah jadi konten reaksi siap upload hanya dalam 5-10 menit. Langsung publish, langsung viral!",
    "benefits.speed.stat": "Proses",
    "benefits.scale.title": "Skalabilitas Unlimited",
    "benefits.scale.desc": "Mau produksi 1 video atau 100 video, prosesnya sama mudahnya. Bulk processing untuk content creator pro.",
    "benefits.scale.stat": "Videos",
    
    // Use Cases
    "usecases.title": "Kasus",
    "usecases.title.highlight": "Penggunaan",
    "usecases.description": "Berbagai cara content creator menggunakan Reactify untuk konten viral mereka",
    "usecases.youtube.title": "Konten YouTube",
    "usecases.youtube.desc": "Bikin video reaksi untuk channel YouTube dengan cepat dan profesional",
    "usecases.youtube.ex1": "React ke trending video & viral moments",
    "usecases.youtube.ex2": "Commentary video dengan narasi AI",
    "usecases.youtube.ex3": "Review & analysis video",
    "usecases.tiktok.title": "TikTok & Shorts",
    "usecases.tiktok.desc": "Konten pendek yang viral dengan editing otomatis",
    "usecases.tiktok.ex1": "React ke TikTok viral",
    "usecases.tiktok.ex2": "Instagram Reels & YouTube Shorts",
    "usecases.tiktok.ex3": "Meme reaction videos",
    "usecases.business.title": "Brand & Marketing",
    "usecases.business.desc": "Konten marketing dengan branding konsisten",
    "usecases.business.ex1": "Product review & testimonial",
    "usecases.business.ex2": "Behind the scenes content",
    "usecases.business.ex3": "Brand awareness campaign",
    "usecases.education.title": "Konten Edukasi",
    "usecases.education.desc": "Video pembelajaran dengan narasi yang jelas",
    "usecases.education.ex1": "Tutorial & how-to videos",
    "usecases.education.ex2": "Course materials & lessons",
    "usecases.education.ex3": "Educational commentary",
    "usecases.gaming.title": "Gaming Content",
    "usecases.gaming.desc": "React ke gameplay & gaming moments",
    "usecases.gaming.ex1": "Game highlights reaction",
    "usecases.gaming.ex2": "Pro player analysis",
    "usecases.gaming.ex3": "Funny moments compilation",
    "usecases.ecommerce.title": "E-Commerce",
    "usecases.ecommerce.desc": "Review produk dengan format menarik",
    "usecases.ecommerce.ex1": "Unboxing & first impression",
    "usecases.ecommerce.ex2": "Product comparison videos",
    "usecases.ecommerce.ex3": "Shopping haul reactions",
    
    // Testimonials
    "testimonials.title": "Apa Kata",
    "testimonials.title.highlight": "Mereka?",
    "testimonials.description": "Content creator yang sudah merasakan manfaat Reactify",
    "testimonials.1.name": "Andi Pratama",
    "testimonials.1.role": "YouTuber Gaming - 500K Subs",
    "testimonials.1.content": "Reactify bikin workflow editing gue 10x lebih cepat! Sekarang bisa upload 3-4 video reaction per hari. Subscriber naik drastis!",
    "testimonials.2.name": "Siti Nurhaliza",
    "testimonials.2.role": "TikTok Creator - 2M Followers",
    "testimonials.2.content": "Auto subtitle-nya akurat banget! Gak perlu edit manual lagi. Tinggal pilih video, generate, langsung viral. Recommended banget!",
    "testimonials.3.name": "Budi Santoso",
    "testimonials.3.role": "Agency Owner",
    "testimonials.3.content": "Klien gue happy semua karena delivery cepat dan kualitas konsisten. Bulk processing-nya game changer untuk agency seperti gue.",
    "testimonials.4.name": "Maya Anggraini",
    "testimonials.4.role": "Content Creator & Influencer",
    "testimonials.4.content": "Narasi AI-nya natural banget, kayak suara manusia beneran. Watermark otomatis bikin branding gue lebih profesional.",
    "testimonials.5.name": "Reza Aditya",
    "testimonials.5.role": "Freelance Video Editor",
    "testimonials.5.content": "Worth it banget! Balik modal dalam seminggu aja. Sekarang bisa terima lebih banyak project tanpa khawatir deadline.",
    "testimonials.6.name": "Linda Wijaya",
    "testimonials.6.role": "E-Commerce Owner",
    "testimonials.6.content": "Video review produk jadi lebih menarik dan engagement naik 300%. Customer lebih percaya dengan testimoni video.",
    
    // FAQ
    "faq.title": "Pertanyaan",
    "faq.title.highlight": "Sering Ditanya",
    "faq.description": "Jawaban untuk pertanyaan yang paling sering ditanyakan",
    "faq.1.question": "Apakah Reactify bisa digunakan untuk pemula?",
    "faq.1.answer": "Tentu saja! Reactify dirancang dengan UI yang user-friendly. Tidak perlu skill editing video profesional. Tinggal pilih video, atur preferensi, dan klik generate. Sangat mudah digunakan bahkan untuk pemula.",
    "faq.2.question": "Berapa lama proses generate video?",
    "faq.2.answer": "Tergantung durasi dan kompleksitas video, biasanya 5-10 menit untuk video berdurasi 10-15 menit. Bulk processing bisa lebih cepat karena diproses paralel.",
    "faq.3.question": "Apakah bisa custom watermark dengan logo sendiri?",
    "faq.3.answer": "Ya! Kamu bisa upload logo atau gambar sendiri sebagai watermark. Atur posisi, ukuran, dan transparansi sesuai kebutuhan branding kamu.",
    "faq.4.question": "Format video apa saja yang didukung?",
    "faq.4.answer": "Reactify mendukung berbagai format populer: MP4, AVI, MOV, MKV, WebM, FLV untuk input. Output bisa MP4, WebM, atau AVI sesuai kebutuhan platform upload kamu.",
    "faq.5.question": "Apakah subtitle otomatis akurat?",
    "faq.5.answer": "Sangat akurat! Menggunakan Whisper AI dari OpenAI dengan tingkat akurasi tinggi. Mendukung banyak bahasa: Indonesia, Inggris, Melayu, Spanyol, Arab, Hindi, dan lainnya.",
    "faq.6.question": "Berapa banyak video yang bisa diproses sekaligus?",
    "faq.6.answer": "Tidak ada batasan! Dengan fitur bulk processing, kamu bisa memproses puluhan hingga ratusan video sekaligus. Sangat cocok untuk content creator yang produksi massal.",
    "faq.7.question": "Apakah lisensi bisa dipindah ke device lain?",
    "faq.7.answer": "1 lisensi berlaku untuk 1 device. Jika ingin pindah device, hubungi support kami via WhatsApp untuk deactivate di device lama dan activate di device baru.",
    "faq.8.question": "Bagaimana cara mendapat update versi terbaru?",
    "faq.8.answer": "Update gratis untuk semua pengguna berlisensi aktif. Notifikasi update akan muncul di aplikasi, tinggal download dan install versi terbaru.",
    "faq.9.question": "Apakah ada support jika ada kendala?",
    "faq.9.answer": "Ada! Support via WhatsApp langsung. Tim kami siap membantu kendala teknis, tutorial penggunaan, atau pertanyaan lainnya.",
    "faq.10.question": "Apakah Reactify memerlukan koneksi internet?",
    "faq.10.answer": "Ya, untuk fitur AI (narasi, subtitle, judul otomatis) memerlukan koneksi internet. Fitur lain seperti overlay, watermark, dan musik bisa offline.",
    
    // Tech Specs
    "techspecs.title": "Spesifikasi",
    "techspecs.title.highlight": "Teknis",
    "techspecs.description": "Requirements dan spesifikasi lengkap Reactify",
    "techspecs.platform.title": "Platform",
    "techspecs.platform.1": "Windows 10/11 (64-bit)",
    "techspecs.platform.2": "macOS 10.15 atau lebih baru",
    "techspecs.platform.3": "Linux (Ubuntu 20.04+)",
    "techspecs.processor.title": "Processor",
    "techspecs.processor.1": "Intel Core i5 atau setara",
    "techspecs.processor.2": "Recommended: i7 atau lebih tinggi",
    "techspecs.storage.title": "Storage & RAM",
    "techspecs.storage.1": "RAM: Minimal 8GB (16GB recommended)",
    "techspecs.storage.2": "Storage: 2GB untuk aplikasi + space untuk video",
    "techspecs.connection.title": "Koneksi",
    "techspecs.connection.1": "Internet untuk fitur AI",
    "techspecs.connection.2": "Bandwidth recommended: 5 Mbps+",
    "techspecs.formats.title": "Format yang Didukung",
    "techspecs.formats.input": "Input Video",
    "techspecs.formats.output": "Output Video",
    "techspecs.formats.audio": "Audio",
    "techspecs.formats.subtitle": "Subtitle",
    
    // Comparison
    "comparison.title": "Reactify vs",
    "comparison.title.highlight": "Manual Editing",
    "comparison.description": "Lihat perbedaan signifikan antara editing manual dan otomatis",
    "comparison.manual": "Manual Editing",
    "comparison.manual.sub": "Cara Tradisional",
    "comparison.reactify": "Reactify AI",
    "comparison.reactify.sub": "Otomatis & Cepat",
    "comparison.features.1": "Generate narasi otomatis",
    "comparison.features.2": "Subtitle otomatis multi-bahasa",
    "comparison.features.3": "Bulk processing",
    "comparison.features.4": "AI judul SEO-friendly",
    "comparison.features.5": "Watermark otomatis",
    "comparison.features.6": "Template & preset",
    "comparison.features.7": "Video overlay otomatis",
    "comparison.features.8": "Background music auto-sync",
    "comparison.features.9": "Konsistensi kualitas",
    "comparison.features.10": "Update & support",
    "comparison.total": "Total Waktu",
    "comparison.hours": "Jam",
    "comparison.minutes": "Menit",
    "comparison.per.video": "per video",
  },
  en: {
    // Navbar
    "nav.features": "Features",
    "nav.pricing": "Pricing",
    "nav.contact": "Contact",
    
    // Hero
    "hero.badge": "AI-Powered Video Reaction Generator",
    "hero.title.reactify": "Reactify",
    "hero.title.main": "Create Viral Reaction Videos in Minutes",
    "hero.description": "Automated, professional reaction videos ready to upload. AI-powered for content creators who want to go viral!",
    "hero.cta.start": "Get Started",
    "hero.cta.features": "View Features",
    "hero.stat.voices": "30+ AI Voices",
    "hero.stat.subtitle": "Auto Subtitle",
    "hero.stat.bulk": "Bulk Processing",
    
    // Demo
    "demo.badge": "Demo Video",
    "demo.title": "See Reactify in Action",
    "demo.subtitle": "Watch how Reactify transforms regular videos into viral reaction content in minutes",
    "demo.description": "The demo video shows the entire process from selecting a video to the final result ready to upload",
    
    // Problem
    "problem.title": "Why Choose",
    "problem.title.highlight": "Reactify?",
    "problem.description": "Creating viral reaction videos takes time. With Reactify, everything is automated.",
    "problem.without.title": "Without Reactify",
    "problem.without.subtitle": "Complex & Time-Consuming",
    "problem.without.1": "Record audio narration manually",
    "problem.without.2": "Edit videos one by one",
    "problem.without.3": "Add subtitles manually",
    "problem.without.4": "Apply watermark & music",
    "problem.without.5": "Render repeatedly",
    "problem.without.6": "Total time: Hours per video",
    "problem.with.title": "With Reactify",
    "problem.with.subtitle": "Fast, Easy & Automated",
    "problem.with.1": "Select target video",
    "problem.with.2": "AI generates narration automatically",
    "problem.with.3": "Auto subtitles in seconds",
    "problem.with.4": "Watermark & music auto-apply",
    "problem.with.5": "Bulk process multiple videos at once",
    "problem.with.6": "Total time: Just minutes!",
    
    // Features
    "features.title": "Key",
    "features.title.highlight": "Features",
    "features.description": "Everything you need to create professional and viral reaction videos",
    "features.narration.title": "AI Auto Narration",
    "features.narration.desc": "30+ Gemini TTS voice options with various styles: funny, dramatic, investigative, educational, and more.",
    "features.subtitle.title": "Auto Subtitle",
    "features.subtitle.desc": "Generate automatic subtitles with Whisper AI. Supports multiple languages and customizable styling.",
    "features.music.title": "Background Music & Custom Audio",
    "features.music.desc": "Add background music to bring videos to life. Adjust volume and use your own external audio.",
    "features.watermark.title": "Watermark & Branding",
    "features.watermark.desc": "Protect videos with text watermark or logo. Adjust position, size, and opacity as needed.",
    "features.overlay.title": "Video Overlay",
    "features.overlay.desc": "Add manual video overlay for reactions. Split or corner mode with auto overlay.",
    "features.ai.title": "AI Auto Title",
    "features.ai.desc": "Generate catchy & SEO-friendly video titles automatically to maximize views.",
    "features.bulk.title": "Bulk Processing",
    "features.bulk.desc": "Process multiple videos at once in one folder. Save time for mass production.",
    "features.ui.title": "Modern Interface",
    "features.ui.desc": "Modern UI with Dark/Light Mode. Easy navigation with Log, Video Info, Script & Settings tabs.",
    
    // Target Audience
    "audience.title": "Who Should",
    "audience.title.highlight": "Use Reactify?",
    "audience.1.title": "YouTuber & TikToker",
    "audience.1.desc": "Quick reaction content ready to go viral",
    "audience.2.title": "Meme Content Creator",
    "audience.2.desc": "Instant editing for short videos",
    "audience.3.title": "Brand & Influencer",
    "audience.3.desc": "Add automatic watermark & branding",
    "audience.4.title": "Agency/Freelancer",
    "audience.4.desc": "Process multiple videos for clients",
    
    // How it works
    "howitworks.title": "How",
    "howitworks.title.highlight": "Reactify Works",
    "howitworks.description": "Just 3 simple steps to professional reaction videos",
    "howitworks.step1.title": "Select Video",
    "howitworks.step1.desc": "Upload or select the video to process",
    "howitworks.step2.title": "Set Preferences",
    "howitworks.step2.desc": "Configure narration, subtitle, music, watermark, and overlay",
    "howitworks.step3.title": "Generate & Done",
    "howitworks.step3.desc": "Click generate, wait a moment, reaction video ready to upload!",
    
    // Pricing
    "pricing.title": "Special",
    "pricing.title.highlight": "Price",
    "pricing.description": "Small investment for big productivity",
    "pricing.badge": "Official & Secure License",
    "pricing.per.year": "/ year",
    "pricing.license": "1 license for 1 device",
    "pricing.feature.1": "All features without limits",
    "pricing.feature.2": "30+ Gemini TTS AI voices",
    "pricing.feature.3": "Auto multi-language subtitles",
    "pricing.feature.4": "Unlimited bulk processing",
    "pricing.feature.5": "Custom watermark & branding",
    "pricing.feature.6": "Manual & auto video overlay",
    "pricing.feature.7": "AI auto title",
    "pricing.feature.8": "Free updates",
    "pricing.feature.9": "WhatsApp support",
    "pricing.license.year": "License valid for 1 full year",
    "pricing.license.support": "Free updates & support",
    "pricing.cta": "Activate Now via WhatsApp",
    
    // CTA
    "cta.title": "Don't Waste Time on Manual Editing",
    "cta.description": "With Reactify, focus on creating content ideas while AI handles the editing automatically.",
    "cta.button": "Chat via WhatsApp",
    "cta.contact": "or contact:",
    "cta.stat.voices": "AI Voices",
    "cta.stat.faster": "Faster",
    "cta.stat.auto": "Automated",
    
    // Footer
    "footer.tagline": "AI-Powered Video Reaction Generator",
    "footer.product": "Product",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.howitworks": "How It Works",
    "footer.support": "Support",
    "footer.contact": "Contact",
    "footer.whatsapp": "WhatsApp",
    "footer.email": "Email",
    "footer.developed": "Developed by",
    "footer.rights": "All rights reserved.",
    
    // Benefits
    "benefits.title": "Why Choose",
    "benefits.title.highlight": "Reactify?",
    "benefits.description": "Real benefits you'll experience immediately for your content business",
    "benefits.time.title": "Massive Time Savings",
    "benefits.time.desc": "What used to take hours of editing now takes just minutes. Focus on content ideas, not editing.",
    "benefits.time.stat": "Time Saved",
    "benefits.viral.title": "More Productive Content",
    "benefits.viral.desc": "Produce 3x more videos in the same time. More content = more viral opportunities.",
    "benefits.viral.stat": "More Productive",
    "benefits.cost.title": "Maximum ROI",
    "benefits.cost.desc": "One-time investment, use for a full year. Save on editor costs, premium editing software, and production time.",
    "benefits.cost.stat": "Positive ROI",
    "benefits.quality.title": "Consistent Quality",
    "benefits.quality.desc": "Video output always HD with professional quality. Clean subtitles, clear audio, consistent branding.",
    "benefits.quality.stat": "Output",
    "benefits.speed.title": "Super Fast Process",
    "benefits.speed.desc": "From raw video to ready-to-upload reaction content in just 5-10 minutes. Publish immediately, go viral instantly!",
    "benefits.speed.stat": "Process",
    "benefits.scale.title": "Unlimited Scalability",
    "benefits.scale.desc": "Whether producing 1 or 100 videos, the process is equally easy. Bulk processing for pro content creators.",
    "benefits.scale.stat": "Videos",
    
    // Use Cases
    "usecases.title": "Use",
    "usecases.title.highlight": "Cases",
    "usecases.description": "Various ways content creators use Reactify for their viral content",
    "usecases.youtube.title": "YouTube Content",
    "usecases.youtube.desc": "Create reaction videos for YouTube channels quickly and professionally",
    "usecases.youtube.ex1": "React to trending videos & viral moments",
    "usecases.youtube.ex2": "Commentary videos with AI narration",
    "usecases.youtube.ex3": "Review & analysis videos",
    "usecases.tiktok.title": "TikTok & Shorts",
    "usecases.tiktok.desc": "Viral short content with automatic editing",
    "usecases.tiktok.ex1": "React to viral TikToks",
    "usecases.tiktok.ex2": "Instagram Reels & YouTube Shorts",
    "usecases.tiktok.ex3": "Meme reaction videos",
    "usecases.business.title": "Brand & Marketing",
    "usecases.business.desc": "Marketing content with consistent branding",
    "usecases.business.ex1": "Product reviews & testimonials",
    "usecases.business.ex2": "Behind the scenes content",
    "usecases.business.ex3": "Brand awareness campaigns",
    "usecases.education.title": "Educational Content",
    "usecases.education.desc": "Learning videos with clear narration",
    "usecases.education.ex1": "Tutorials & how-to videos",
    "usecases.education.ex2": "Course materials & lessons",
    "usecases.education.ex3": "Educational commentary",
    "usecases.gaming.title": "Gaming Content",
    "usecases.gaming.desc": "React to gameplay & gaming moments",
    "usecases.gaming.ex1": "Game highlights reactions",
    "usecases.gaming.ex2": "Pro player analysis",
    "usecases.gaming.ex3": "Funny moments compilations",
    "usecases.ecommerce.title": "E-Commerce",
    "usecases.ecommerce.desc": "Product reviews in engaging format",
    "usecases.ecommerce.ex1": "Unboxing & first impressions",
    "usecases.ecommerce.ex2": "Product comparison videos",
    "usecases.ecommerce.ex3": "Shopping haul reactions",
    
    // Testimonials
    "testimonials.title": "What They",
    "testimonials.title.highlight": "Say?",
    "testimonials.description": "Content creators who have experienced Reactify benefits",
    "testimonials.1.name": "John Anderson",
    "testimonials.1.role": "Gaming YouTuber - 500K Subs",
    "testimonials.1.content": "Reactify makes my editing workflow 10x faster! Now I can upload 3-4 reaction videos per day. Subscribers skyrocketed!",
    "testimonials.2.name": "Sarah Mitchell",
    "testimonials.2.role": "TikTok Creator - 2M Followers",
    "testimonials.2.content": "The auto subtitles are incredibly accurate! No more manual editing. Just select video, generate, and go viral instantly. Highly recommended!",
    "testimonials.3.name": "Michael Chen",
    "testimonials.3.role": "Agency Owner",
    "testimonials.3.content": "All my clients are happy because of fast delivery and consistent quality. Bulk processing is a game changer for agencies like mine.",
    "testimonials.4.name": "Emma Rodriguez",
    "testimonials.4.role": "Content Creator & Influencer",
    "testimonials.4.content": "The AI narration sounds so natural, like real human voice. Auto watermark makes my branding more professional.",
    "testimonials.5.name": "David Kim",
    "testimonials.5.role": "Freelance Video Editor",
    "testimonials.5.content": "Totally worth it! Paid for itself in just a week. Now I can take on more projects without worrying about deadlines.",
    "testimonials.6.name": "Lisa Wang",
    "testimonials.6.role": "E-Commerce Owner",
    "testimonials.6.content": "Product review videos are more engaging and engagement increased 300%. Customers trust video testimonials more.",
    
    // FAQ
    "faq.title": "Frequently Asked",
    "faq.title.highlight": "Questions",
    "faq.description": "Answers to the most commonly asked questions",
    "faq.1.question": "Can beginners use Reactify?",
    "faq.1.answer": "Absolutely! Reactify is designed with a user-friendly UI. No professional video editing skills needed. Just select video, set preferences, and click generate. Very easy to use even for beginners.",
    "faq.2.question": "How long does video generation take?",
    "faq.2.answer": "Depends on duration and video complexity, typically 5-10 minutes for a 10-15 minute video. Bulk processing can be faster as it's processed in parallel.",
    "faq.3.question": "Can I use custom logo watermarks?",
    "faq.3.answer": "Yes! You can upload your own logo or image as a watermark. Adjust position, size, and transparency according to your branding needs.",
    "faq.4.question": "What video formats are supported?",
    "faq.4.answer": "Reactify supports various popular formats: MP4, AVI, MOV, MKV, WebM, FLV for input. Output can be MP4, WebM, or AVI depending on your upload platform needs.",
    "faq.5.question": "Are automatic subtitles accurate?",
    "faq.5.answer": "Very accurate! Uses Whisper AI from OpenAI with high accuracy. Supports many languages: Indonesian, English, Malay, Spanish, Arabic, Hindi, and more.",
    "faq.6.question": "How many videos can be processed at once?",
    "faq.6.answer": "No limits! With bulk processing feature, you can process dozens to hundreds of videos simultaneously. Perfect for content creators doing mass production.",
    "faq.7.question": "Can licenses be transferred to another device?",
    "faq.7.answer": "1 license is valid for 1 device. To transfer devices, contact our support via WhatsApp to deactivate on old device and activate on new device.",
    "faq.8.question": "How do I get the latest version updates?",
    "faq.8.answer": "Free updates for all active license holders. Update notifications appear in the app, just download and install the latest version.",
    "faq.9.question": "Is there support if I have issues?",
    "faq.9.answer": "Yes! Direct WhatsApp support. Our team is ready to help with technical issues, usage tutorials, or other questions.",
    "faq.10.question": "Does Reactify require internet connection?",
    "faq.10.answer": "Yes, for AI features (narration, subtitles, auto titles) internet connection is required. Other features like overlay, watermark, and music can work offline.",
    
    // Tech Specs
    "techspecs.title": "Technical",
    "techspecs.title.highlight": "Specifications",
    "techspecs.description": "Complete Reactify requirements and specifications",
    "techspecs.platform.title": "Platform",
    "techspecs.platform.1": "Windows 10/11 (64-bit)",
    "techspecs.platform.2": "macOS 10.15 or newer",
    "techspecs.platform.3": "Linux (Ubuntu 20.04+)",
    "techspecs.processor.title": "Processor",
    "techspecs.processor.1": "Intel Core i5 or equivalent",
    "techspecs.processor.2": "Recommended: i7 or higher",
    "techspecs.storage.title": "Storage & RAM",
    "techspecs.storage.1": "RAM: Minimum 8GB (16GB recommended)",
    "techspecs.storage.2": "Storage: 2GB for app + space for videos",
    "techspecs.connection.title": "Connection",
    "techspecs.connection.1": "Internet for AI features",
    "techspecs.connection.2": "Recommended bandwidth: 5 Mbps+",
    "techspecs.formats.title": "Supported Formats",
    "techspecs.formats.input": "Input Video",
    "techspecs.formats.output": "Output Video",
    "techspecs.formats.audio": "Audio",
    "techspecs.formats.subtitle": "Subtitle",
    
    // Comparison
    "comparison.title": "Reactify vs",
    "comparison.title.highlight": "Manual Editing",
    "comparison.description": "See the significant difference between manual and automated editing",
    "comparison.manual": "Manual Editing",
    "comparison.manual.sub": "Traditional Way",
    "comparison.reactify": "Reactify AI",
    "comparison.reactify.sub": "Automated & Fast",
    "comparison.features.1": "Auto narration generation",
    "comparison.features.2": "Auto multi-language subtitles",
    "comparison.features.3": "Bulk processing",
    "comparison.features.4": "SEO-friendly AI titles",
    "comparison.features.5": "Automatic watermark",
    "comparison.features.6": "Templates & presets",
    "comparison.features.7": "Automatic video overlay",
    "comparison.features.8": "Auto-sync background music",
    "comparison.features.9": "Quality consistency",
    "comparison.features.10": "Updates & support",
    "comparison.total": "Total Time",
    "comparison.hours": "Hours",
    "comparison.minutes": "Minutes",
    "comparison.per.video": "per video",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("id");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
